services:
  - type: web
    name: e-ticket-backend
    env: php
    plan: free  # or starter, depending on your needs
    buildCommand: |
      
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: maglev.proxy.rlwy.net
      - key: DB_PORT
        value: 18816
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false